#' Ensemble Clustering Algorithms for Single-Cell Data
#'
#' This function performs ensemble clustering on single-cell RNA-seq data using
#' multiple algorithms including CSPA (Cluster-based Similarity Partitioning Algorithm),
#' MCLA (Meta-CLustering Algorithm), and HGSC (Hypergraph Spectral Clustering).
#'
#' @rdname ensemble_clustering
#' 
#' @param expression_data A matrix or data frame containing the gene expression data.
#'   Rows represent cells and columns represent genes.
#' @param true_labels Optional vector of true cluster labels for validation.
#'   If provided, Adjusted Rand Index (ARI) will be calculated.
#' @param H_matrix A hypergraph matrix generated by \code{generate_all_hypergraphs}.
#'   Must be a list containing matrices H, HH, H_sil, HH_sil, H_ch, HH_ch,
#'   H_db, HH_db, H_ave, HH_ave.
#' @param k Optional integer specifying the number of clusters.
#'   If NULL, optimal k will be estimated automatically.
#' @param ensemble_methods Character vector specifying which ensemble methods to use.
#'   Options include: "CSPA_Hc", "CSPA_Louvain", "CSPA_Leiden", "MCLA_Hc",
#'   "MCLA_Louvain", "MCLA_Leiden", "HGSC".
#'
#' @return A list containing:
#' \describe{
#'   \item{ensemble_clusters}{List of clustering results for each method}
#'   \item{ensemble_ari}{List of ARI values if true_labels provided}
#'   \item{quality_indices}{List of quality indices for each method}
#' }
#'
#' @details
#' The function implements several ensemble clustering algorithms:
#' \itemize{
#'   \item CSPA (Cluster-based Similarity Partitioning Algorithm): Uses hierarchical clustering, Louvain, or Leiden community detection
#'   \item MCLA (Meta-CLustering Algorithm): Meta-clustering approach with hierarchical clustering, Louvain, or Leiden
#'   \item HGSC (Hypergraph Spectral Clustering): Spectral clustering on hypergraphs
#' }
#'
#' Quality indices calculated include:
#' \itemize{
#'   \item Silhouette score
#'   \item Calinski-Harabasz index
#'   \item Davies-Bouldin index
#'   \item Dunn index
#' }
#'
#'
#' @importFrom cluster silhouette
#' @importFrom fpc calinhara
#' @importFrom igraph graph_from_adjacency_matrix cluster_louvain cluster_leiden membership
#' @importFrom mclust adjustedRandIndex
#' @importFrom stats kmeans hclust cutree dist
#' @importFrom utils head
#' @importFrom methods new
#' @importFrom SummarizedExperiment assay
#' @importFrom stats as.dist
#' @importFrom parallel makeCluster stopCluster parLapply clusterExport clusterEvalQ detectCores
#'
#' @examples
#' # Load required packages
#' library(scRNAseq)
#' library(SingleCellExperiment)
#' 
#' # Complete ScEnsemble pipeline
#' Pollen <- PollenGliaData()
#' ann <- colData(Pollen)[["Inferred Cell Type"]]
#' scens <- CreateScEnsemble(Pollen, ann)
#' 
#' # Run full pipeline
#' scens <- run_individual_algorithms(scens)
#' scens <- calculate_all_validation_indices(scens)
#' scens <- generate_all_hypergraphs(scens)
#' scens <- ensemble_clustering(scens)
#'
#' @export
setMethod("ensemble_clustering", "ScEnsemble",
          function(object,
                   expression_data,
                   true_labels = NULL,
                   H_matrix,
                   k = NULL,
                   ensemble_methods = c("CSPA_Hc", "CSPA_Louvain", "CSPA_Leiden",
                                        "MCLA_Hc", "MCLA_Louvain", "MCLA_Leiden", "HGSC"),
                   leiden_n_bootstrap = 10,
                   leiden_method = c("bootstrap", "silhouette"),
                   n_cores = 1L,
                   ...) {
            leiden_method <- match.arg(leiden_method)
            
            
            expression_data <- as.matrix(assay(object@sce))
            true_labels <- object@annotation
            
            # Retrieve data 
            H_matrix <- object@hypergraphs
            
            # Extract matrices from H_matrix
            H <- H_matrix$H
            HH <- H_matrix$HH
            H_sil <- H_matrix$H_sil
            HH_sil <- H_matrix$HH_sil
            H_ch <- H_matrix$H_ch
            HH_ch <- H_matrix$HH_ch
            H_db <- H_matrix$H_db
            HH_db <- H_matrix$HH_db
            H_ave <- H_matrix$H_ave
            HH_ave <- H_matrix$HH_ave
            
            # Input validation
            if (!is.matrix(expression_data) && !is.data.frame(expression_data)) {
              stop("expression_data must be a matrix or data frame")
            }
            
            if (!is.list(H_matrix)) {
              stop("H_matrix must be a list containing hypergraph matrices")
            }
            
            # Validate ensemble methods
            valid_methods <- c("CSPA_Hc", "CSPA_Louvain", "CSPA_Leiden",
                               "MCLA_Hc", "MCLA_Louvain", "MCLA_Leiden", "HGSC")
            
            if (!all(ensemble_methods %in% valid_methods)) {
              invalid_methods <- setdiff(ensemble_methods, valid_methods)
              stop("Invalid ensemble methods: ", paste(invalid_methods, collapse = ", "))
            }
            
            # Main function that calculates clustering quality indices
            calculate_quality_indices <- function(data, clusters, method_name = "") {
              clusters <- as.numeric(factor(clusters))  
              
              n_clusters <- length(unique(clusters))
              if (n_clusters < 2) {
                warning(sprintf("Method %s produced only %d cluster(s). Skipping quality index calculation.", method_name, n_clusters))
                return(list(silhouette = NA, silhouette_norm = NA,
                            calinski_harabasz = NA, calinski_harabasz_norm = NA,
                            davies_bouldin = NA, davies_bouldin_norm = NA,
                            dunn = NA, dunn_norm = NA))
              }
              
              dist_matrix <- prepare_distance_matrix(data)
              
              # Calculate raw scores
              silhouette_score <- calculate_silhouette(dist_matrix, clusters, method_name)
              ch_score         <- calculate_calinski_harabasz(dist_matrix, clusters, method_name)
              db_score         <- calculate_davies_bouldin(data, clusters, method_name)
              dunn_score       <- calculate_dunn(dist_matrix, clusters, method_name)
              
              
              silhouette_norm <- if (!is.na(silhouette_score)) (silhouette_score + 1) / 2 else NA
              db_norm <- if (!is.na(db_score)) 1 / (1 + db_score) else NA
              ch_norm <- if (!is.na(ch_score)) log(1 + ch_score) / (1 + log(1 + ch_score)) else NA
              dunn_norm <- if (!is.na(dunn_score)) dunn_score / (1 + dunn_score) else NA
              
              list(
                silhouette = silhouette_score, silhouette_norm = silhouette_norm,
                calinski_harabasz = ch_score, calinski_harabasz_norm = ch_norm,
                davies_bouldin = db_score, davies_bouldin_norm = db_norm,
                dunn = dunn_score, dunn_norm = dunn_norm)
            }
            
            prepare_distance_matrix <- function(data) {
              # If it is already a dist object, return it directly
              if (inherits(data, "dist")) return(data)
              
              # If it is a square matrix (can be similarity or distance)
              if (is.matrix(data) && nrow(data) == ncol(data)) {
                diagonal_mean <- mean(diag(data), na.rm = TRUE)
                
                # If diagonal is ~1, this is the similarity matrix (eg correlation, cosine)
                if (diagonal_mean > 0.9) {
                  # distance from similarity: distance = 1 - similarity
                  distance_matrix <- 1 - data
                  diag(distance_matrix) <- 0
                  return(as.dist(distance_matrix))
                } else {
                  # If diagonal is ~0, this can already be distance
                  return(as.dist(data))
                }
              }
              
              # If it is a data frame or data matrix (raw data)
              if (is.data.frame(data) || is.matrix(data)) {
                return(dist(data, method = "euclidean"))
              }
              
              stop("Data format not recognized. Please provide a data.frame, matrix, or dist object.")
            }
            
            
            # Silhouette skoru
            calculate_silhouette <- function(dist_matrix, clusters, method_name) {
              tryCatch({
                mean(cluster::silhouette(clusters, dist_matrix)[, 3])
              }, error = function(e) {
                warning(sprintf("Silhouette failed for %s: %s", method_name, e$message))
                NA
              })
            }
            
            # Calinski-Harabasz score
            calculate_calinski_harabasz <- function(dist_matrix, clusters, method_name) {
              tryCatch({
                val <- fpc::calinhara(as.matrix(dist_matrix), clusters)
                if (!is.finite(val)) return(NA_real_)
                val
              }, error = function(e) {
                warning(sprintf("Calinski-Harabasz failed for %s: %s", method_name, e$message))
                NA
              })
            }

            # Dunn score — fast implementation: converts dist to matrix ONCE
            calculate_dunn <- function(dist_matrix, clusters, method_name) {
              tryCatch({
                d  <- as.matrix(dist_matrix)
                uq <- unique(clusters)
                intra <- 0
                inter <- Inf
                for (i in uq) {
                  ci <- which(clusters == i)
                  if (length(ci) > 1) intra <- max(intra, max(d[ci, ci]))
                  for (j in uq[uq > i]) {
                    cj <- which(clusters == j)
                    inter <- min(inter, min(d[ci, cj]))
                  }
                }
                val <- inter / intra
                if (!is.finite(val)) return(NA_real_)
                val
              }, error = function(e) {
                warning(sprintf("Dunn failed for %s: %s", method_name, e$message))
                NA
              })
            }
            
            # Davies-Bouldin score
            calculate_davies_bouldin <- function(data, clusters, method_name) {
              tryCatch({
                if (inherits(data, "dist")) return(NA)
                manual_davies_bouldin(as.matrix(data), clusters)
              }, error = function(e) {
                warning(sprintf("Davies-Bouldin failed for %s: %s", method_name, e$message))
                NA
              })
            }
            
            # Manuel Davies-Bouldin calculator
            manual_davies_bouldin <- function(data, clusters) {
              clusters <- as.numeric(factor(clusters))  
              unique_clusters <- unique(clusters)
              n_clusters <- length(unique_clusters)
              
              centers <- t(vapply(unique_clusters, function(k) {
                colMeans(data[clusters == k, , drop = FALSE])
              }, FUN.VALUE = numeric(ncol(data))))  
              
              within_scatter <- vapply(unique_clusters, function(k) {
                pts <- data[clusters == k, , drop = FALSE]
                if (nrow(pts) < 2) return(0)
                mean(sqrt(rowSums((pts - matrix(colMeans(pts), nrow(pts), ncol(data), byrow = TRUE))^2)))
              }, FUN.VALUE = numeric(1))  
              
              between_distances <- as.matrix(dist(centers))
              
              db_index <- vapply(1:n_clusters, function(i) {
                max(vapply(setdiff(1:n_clusters, i), function(j) {
                  (within_scatter[i] + within_scatter[j]) / between_distances[i, j]
                }, FUN.VALUE = numeric(1)))  
              }, FUN.VALUE = numeric(1)) 
              
              mean(db_index)
            }
            
            
            
            
            # ── Parallel cluster setup ──────────────────────────────────────
            .cl <- NULL
            if (n_cores > 1L) {
              .cl <- tryCatch({
                cl_tmp <- parallel::makeCluster(n_cores, type = "PSOCK")
                parallel::clusterEvalQ(cl_tmp, {
                  library(cluster); library(fpc); library(clValid); library(igraph); library(mclust)
                })
                parallel::clusterExport(cl_tmp, c(
                  "calculate_quality_indices", "prepare_distance_matrix",
                  "calculate_silhouette", "calculate_calinski_harabasz",
                  "calculate_dunn", "calculate_davies_bouldin", "manual_davies_bouldin"
                ), envir = environment())
                cl_tmp
              }, error = function(e) {
                message("Parallel cluster could not be created, running serially: ", e$message)
                NULL
              })
              if (!is.null(.cl)) on.exit(parallel::stopCluster(.cl), add = TRUE)
            }
            .par_lapply <- function(X, FUN, ...) {
              if (!is.null(.cl)) parallel::parLapply(.cl, X, FUN, ...) else lapply(X, FUN, ...)
            }
            # ────────────────────────────────────────────────────────────────

            results <- list()
            results$ensemble_clusters <- list()
            results$ensemble_ari <- list()
            results$quality_indices <- list()  
            
            # ============================================================
            message("Ensemble clustering algorithms running...")
            
            # ============================================================
            # CSPA (Cluster-based Similarity Partitioning Algorithm)
            # ============================================================
            if ("CSPA_Hc" %in% ensemble_methods) {
              message("Running CSPA_Hc algorithm...")
              
              cspa_ensemble <- function(H_weighted) {
                # This function implements the CSPA ensemble clustering algorithm using a weighted hypergraph matrix.
                
                # Converts from a similarity matrix to a distance matrix.
                D <- 1 - H_weighted
                
                # Apply hierarchical clustering
                hc <- hclust(as.dist(D), method = "average")
                
                # Determine the optimal number of clusters using the silhouette method
                k_range <- 2:10  
                sil_scores <- numeric(length(k_range))
                
                for (i in seq_along(k_range)) {
                  k_val <- k_range[i]
                  clusters <- cutree(hc, k = k_val)
                  
                  # At least 2 clusters are required to calculate the silhouette value
                  if (length(unique(clusters)) > 1) {
                    sil <- cluster::silhouette(clusters, as.dist(D))
                    sil_scores[i] <- mean(sil[, 3])
                  } else {
                    sil_scores[i] <- 0
                  }
                }
                
                optimal_k <- k_range[which.max(sil_scores)]
                
                final_clusters <- cutree(hc, k = optimal_k)
                
                return(final_clusters)
              }
              
              # Apply the CSPA algorithm to different hypergraph matrices
              results$ensemble_clusters$cspa_hc <- list(
                standard = cspa_ensemble(HH),
                silhouette = cspa_ensemble(HH_sil),
                ch = cspa_ensemble(HH_ch),
                db = cspa_ensemble(HH_db),
                average = cspa_ensemble(HH_ave)
              )

              message("Computing CSPA_Hc quality indices...")
              .qi_cspa_hc <- list(
                standard   = list(data=HH,      cl=results$ensemble_clusters$cspa_hc$standard,   nm="CSPA_Hc_standard"),
                silhouette = list(data=HH_sil,  cl=results$ensemble_clusters$cspa_hc$silhouette, nm="CSPA_Hc_silhouette"),
                ch         = list(data=HH_ch,   cl=results$ensemble_clusters$cspa_hc$ch,         nm="CSPA_Hc_ch"),
                db         = list(data=HH_db,   cl=results$ensemble_clusters$cspa_hc$db,         nm="CSPA_Hc_db"),
                average    = list(data=HH_ave,  cl=results$ensemble_clusters$cspa_hc$average,    nm="CSPA_Hc_average")
              )
              results$quality_indices$cspa_hc <- .par_lapply(.qi_cspa_hc, function(t)
                calculate_quality_indices(t$data, t$cl, t$nm))

              if (!is.null(true_labels)) {
                results$ensemble_ari$cspa_hc <- list(
                  standard   = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_hc$standard),
                  silhouette = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_hc$silhouette),
                  ch         = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_hc$ch),
                  db         = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_hc$db),
                  average    = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_hc$average)
                )
              }
            }
            
            # ============================================================
            # CSPA with Louvain Community Detection
            # ============================================================
            if ("CSPA_Louvain" %in% ensemble_methods) {
              message("Running CSPA_Louvain algorithm...")
              
              cspa_louvain_ensemble <- function(H_weighted) {
                set.seed(42)
                # Create graph from similarity matrix
                g <- igraph::graph_from_adjacency_matrix(H_weighted, mode = "undirected", weighted = TRUE)

                # Apply Louvain community detection algorithm
                louvain_result <- igraph::cluster_louvain(g)
                clusters <- igraph::membership(louvain_result)
                
                return(clusters)
              }
              
              results$ensemble_clusters$cspa_louvain <- list(
                standard = cspa_louvain_ensemble(HH),
                silhouette = cspa_louvain_ensemble(HH_sil),
                ch = cspa_louvain_ensemble(HH_ch),
                db = cspa_louvain_ensemble(HH_db),
                average = cspa_louvain_ensemble(HH_ave)
              )

              message("Computing CSPA_Louvain quality indices...")
              .qi_cspa_lou <- list(
                standard   = list(data=HH,      cl=results$ensemble_clusters$cspa_louvain$standard,   nm="CSPA_Louvain_standard"),
                silhouette = list(data=HH_sil,  cl=results$ensemble_clusters$cspa_louvain$silhouette, nm="CSPA_Louvain_silhouette"),
                ch         = list(data=HH_ch,   cl=results$ensemble_clusters$cspa_louvain$ch,         nm="CSPA_Louvain_ch"),
                db         = list(data=HH_db,   cl=results$ensemble_clusters$cspa_louvain$db,         nm="CSPA_Louvain_db"),
                average    = list(data=HH_ave,  cl=results$ensemble_clusters$cspa_louvain$average,    nm="CSPA_Louvain_average")
              )
              results$quality_indices$cspa_louvain <- .par_lapply(.qi_cspa_lou, function(t)
                calculate_quality_indices(t$data, t$cl, t$nm))

              if (!is.null(true_labels)) {
                results$ensemble_ari$cspa_louvain <- list(
                  standard = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_louvain$standard),
                  silhouette = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_louvain$silhouette),
                  ch = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_louvain$ch),
                  db = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_louvain$db),
                  average = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_louvain$average)
                )
              }
            }
            
            # ============================================================
            # CSPA with Leiden Community Detection
            # ============================================================
            if ("CSPA_Leiden" %in% ensemble_methods) {
              message("Running CSPA_Leiden algorithm...")
              
              cspa_leiden_ensemble <- function(H_weighted, resolution=1.0) {
                set.seed(42)
                g <- igraph::graph_from_adjacency_matrix(H_weighted, mode = "undirected", weighted = TRUE)
                
                leiden_result <- igraph::cluster_leiden(g, resolution = resolution)
                
                clusters <- igraph::membership(leiden_result)
                
                return(clusters)
              }
              
              # Bootstrap-based stability optimisation for CSPA Leiden.
              # Ground-truth labels are NOT used at any stage.
              # Workflow (Monti et al. 2003 consensus-clustering framework):
              #   1. Run Leiden on full co-association matrix → reference partition C_ref
              #   2. Repeat n_bootstrap times:
              #        a. Draw 80 % of cells (without replacement)
              #        b. Run Leiden on the induced submatrix → C_sub
              #        c. ARI(C_ref[subsample], C_sub)  — both purely algorithmic
              #   3. Stability score = mean ARI across bootstrap replicates
              #   4. Select resolution with highest stability score
              # Graph is built once (resolution-independent) to save time.
              optimize_resolution_cspa <- function(H_weighted, label = "CSPA",
                                                   n_bootstrap = 10,
                                                   subsample_fraction = 0.8) {
                res_range <- seq(0.2, 2.0, by = 0.2)
                N <- nrow(H_weighted)
                g_full <- igraph::graph_from_adjacency_matrix(
                  H_weighted, mode = "undirected", weighted = TRUE)

                # Export current-scope state to workers
                if (!is.null(.cl)) {
                  parallel::clusterExport(.cl,
                    c("g_full", "H_weighted", "N", "n_bootstrap", "subsample_fraction"),
                    envir = environment())
                  parallel::clusterEvalQ(.cl, { library(igraph); library(mclust) })
                }

                stab_results <- .par_lapply(as.list(res_range), function(r) {
                  set.seed(42)
                  ref_clusters <- tryCatch(
                    as.integer(igraph::membership(
                      igraph::cluster_leiden(g_full, resolution = r, n_iterations = 2L))),
                    error = function(e) NULL)
                  if (is.null(ref_clusters) || length(unique(ref_clusters)) < 2)
                    return(list(r = r, stab = -Inf))

                  ari_scores <- numeric(n_bootstrap)
                  for (b in seq_len(n_bootstrap)) {
                    set.seed(42 + b)
                    idx    <- sample(N, round(subsample_fraction * N), replace = FALSE)
                    H_sub  <- H_weighted[idx, idx]
                    g_sub  <- igraph::graph_from_adjacency_matrix(
                      H_sub, mode = "undirected", weighted = TRUE)
                    sub_cl <- tryCatch(
                      as.integer(igraph::membership(
                        igraph::cluster_leiden(g_sub, resolution = r, n_iterations = 2L))),
                      error = function(e) NULL)
                    if (is.null(sub_cl) || length(unique(sub_cl)) < 2) {
                      ari_scores[b] <- 0; next
                    }
                    ari_val <- tryCatch(
                      mclust::adjustedRandIndex(ref_clusters[idx], sub_cl),
                      error = function(e) NA_real_)
                    ari_scores[b] <- if (!is.finite(ari_val)) 0 else ari_val
                  }
                  stab <- mean(ari_scores, na.rm = TRUE)
                  list(r = r, stab = if (!is.finite(stab) || stab <= 0) -Inf else stab)
                })

                best_stabs <- vapply(stab_results, `[[`, numeric(1), "stab")
                best_idx   <- which.max(best_stabs)
                if (length(best_idx) == 0 || !is.finite(best_stabs[best_idx]) || best_stabs[best_idx] <= 0) {
                  best_res <- 1.0; best_stability <- 0
                } else {
                  best_res       <- stab_results[[best_idx]]$r
                  best_stability <- best_stabs[best_idx]
                }
                message(sprintf("    %s Leiden optimum resolution: %.2f (bootstrap stability: %.4f)",
                                label, best_res, best_stability))
                return(best_res)
              }

              # Silhouette-based resolution selection for CSPA Leiden.
              # Selects the resolution maximising mean silhouette width on the
              # co-association matrix.  Label-free, but NOTE: silhouette is also
              # reported as an evaluation metric — use only for comparison purposes.
              optimize_resolution_cspa_sil <- function(H_weighted, label = "CSPA") {
                res_range <- seq(0.2, 2.0, by = 0.2)
                dist_mat  <- as.dist(1 - H_weighted)
                g <- igraph::graph_from_adjacency_matrix(
                  H_weighted, mode = "undirected", weighted = TRUE)
                best_res <- NA; best_score <- -Inf
                for (r in res_range) {
                  set.seed(42)
                  cl <- tryCatch(
                    as.integer(igraph::membership(igraph::cluster_leiden(g, resolution = r))),
                    error = function(e) NULL)
                  if (is.null(cl) || length(unique(cl)) < 2) next
                  sc <- tryCatch(
                    mean(cluster::silhouette(cl, dist_mat)[, 3], na.rm = TRUE),
                    error = function(e) NA_real_)
                  if (!is.finite(sc)) next
                  if (sc > best_score) { best_score <- sc; best_res <- r }
                }
                if (is.na(best_res)) best_res <- 1.0
                message(sprintf("    %s Leiden optimum resolution: %.2f (silhouette: %.4f)",
                                label, best_res, ifelse(is.finite(best_score), best_score, 0)))
                return(best_res)
              }

              # Dispatch: choose optimiser based on leiden_method
              run_opt_cspa <- function(H_mat, label) {
                if (leiden_method == "silhouette")
                  optimize_resolution_cspa_sil(H_mat, label)
                else
                  optimize_resolution_cspa(H_mat, label, n_bootstrap = leiden_n_bootstrap)
              }

              resolution_params <- list()
              resolution_params$standard   <- run_opt_cspa(HH,     "CSPA standard")
              resolution_params$silhouette <- run_opt_cspa(HH_sil, "CSPA silhouette")
              resolution_params$ch         <- run_opt_cspa(HH_ch,  "CSPA ch")
              resolution_params$db         <- run_opt_cspa(HH_db,  "CSPA db")
              resolution_params$average    <- run_opt_cspa(HH_ave, "CSPA average")

              results$ensemble_clusters$cspa_leiden <- list(
                standard = cspa_leiden_ensemble(HH, resolution_params$standard),
                silhouette = cspa_leiden_ensemble(HH_sil, resolution_params$silhouette),
                ch = cspa_leiden_ensemble(HH_ch, resolution_params$ch),
                db = cspa_leiden_ensemble(HH_db, resolution_params$db),
                average = cspa_leiden_ensemble(HH_ave, resolution_params$average)
              )

              message("Computing CSPA_Leiden quality indices...")
              .qi_cspa_lei <- list(
                standard   = list(data=HH,      cl=results$ensemble_clusters$cspa_leiden$standard,   nm="CSPA_Leiden_standard"),
                silhouette = list(data=HH_sil,  cl=results$ensemble_clusters$cspa_leiden$silhouette, nm="CSPA_Leiden_silhouette"),
                ch         = list(data=HH_ch,   cl=results$ensemble_clusters$cspa_leiden$ch,         nm="CSPA_Leiden_ch"),
                db         = list(data=HH_db,   cl=results$ensemble_clusters$cspa_leiden$db,         nm="CSPA_Leiden_db"),
                average    = list(data=HH_ave,  cl=results$ensemble_clusters$cspa_leiden$average,    nm="CSPA_Leiden_average")
              )
              results$quality_indices$cspa_leiden <- .par_lapply(.qi_cspa_lei, function(t)
                calculate_quality_indices(t$data, t$cl, t$nm))

              if (!is.null(true_labels)) {
                results$ensemble_ari$cspa_leiden <- list(
                  standard = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_leiden$standard),
                  silhouette = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_leiden$silhouette),
                  ch = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_leiden$ch),
                  db = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_leiden$db),
                  average = adjustedRandIndex(true_labels, results$ensemble_clusters$cspa_leiden$average)
                )
              }
            }
            
            # ============================================================
            # MCLA (Meta-CLustering Algorithm)
            # ============================================================
            if ("MCLA_Hc" %in% ensemble_methods) {
              message("Running MCLA_Hc algorithm...")
              
              mcla_ensemble <- function(H_weighted, k=NULL) {
                # This function implements the MCLA ensemble clustering algorithm using a weighted hypergraph matrix.
                
                # Number of hyperedges (number of columns of H)
                n_hyperedges <- ncol(H_weighted)
                
                # Calculate Jaccard similarity between hyperedges
                J <- matrix(0, n_hyperedges, n_hyperedges)
                
                for (i in 1:(n_hyperedges-1)) {
                  for (j in (i+1):n_hyperedges) {
                    # Calculate Jaccard similarity (intersection/union)
                    # Use real numbers instead of Boolean operators
                    intersection <- sum(pmin(H_weighted[, i], H_weighted[, j]))
                    union <- sum(pmax(H_weighted[, i], H_weighted[, j]))
                    
                    if (union > 0) {
                      J[i, j] <- intersection / union
                      J[j, i] <- J[i, j]  
                    }
                  }
                }
                
                D <- 1 - J
                # Clustering Hyperedges
                hc <- hclust(as.dist(D), method = "average")
                
                
                if (is.null(k)) {
                  k_range <- 2:min(10, n_hyperedges-1)  
                  sil_scores <- numeric(length(k_range))
                  
                  for (i in seq_along(k_range)) {
                    k_val <- k_range[i]
                    clusters <- cutree(hc, k = k_val)
                    
                    if (length(unique(clusters)) > 1) {
                      sil <- cluster::silhouette(clusters, as.dist(D))
                      sil_scores[i] <- mean(sil[, 3])
                    } else {
                      sil_scores[i] <- 0
                    }
                  }
                  
                  optimal_k <- k_range[which.max(sil_scores)]
                } else {
                  optimal_k <- k
                }
                
                meta_clusters <- cutree(hc, k = optimal_k)
                
                # Combine meta-clusters and find the most relevant cluster for each object
                n_samples <- nrow(H_weighted)
                cluster_association <- matrix(0, n_samples, optimal_k)
                
                for (i in 1:optimal_k) {
                  meta_cluster_i <- which(meta_clusters == i)
                  if (length(meta_cluster_i) > 0) {
                    # H columns belonging to this meta-group collect
                    # Use values of H_weighted matrix
                    cluster_association[, i] <- rowSums(H_weighted[, meta_cluster_i, drop = FALSE])
                  }
                }
                
                # Assign each object to the meta-cluster with the highest association
                final_clusters <- apply(cluster_association, 1, which.max)
                
                # Instead of assigning cluster labels randomly, treat them as consecutive numbers starting from 1
                return(as.integer(final_clusters))
              }
              
              results$ensemble_clusters$mcla <- list(
                standard = mcla_ensemble(H),
                silhouette = mcla_ensemble(H_sil),
                ch = mcla_ensemble(H_ch),
                db = mcla_ensemble(H_db),
                average = mcla_ensemble(H_ave)
              )

              message("Computing MCLA_Hc quality indices...")
              .qi_mcla <- list(
                standard   = list(data=HH,      cl=results$ensemble_clusters$mcla$standard,   nm="MCLA_standard"),
                silhouette = list(data=HH_sil,  cl=results$ensemble_clusters$mcla$silhouette, nm="MCLA_silhouette"),
                ch         = list(data=HH_ch,   cl=results$ensemble_clusters$mcla$ch,         nm="MCLA_ch"),
                db         = list(data=HH_db,   cl=results$ensemble_clusters$mcla$db,         nm="MCLA_db"),
                average    = list(data=HH_ave,  cl=results$ensemble_clusters$mcla$average,    nm="MCLA_average")
              )
              results$quality_indices$mcla <- .par_lapply(.qi_mcla, function(t)
                calculate_quality_indices(t$data, t$cl, t$nm))

              if (!is.null(true_labels)) {
                results$ensemble_ari$mcla <- list(
                  standard = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla$standard),
                  silhouette = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla$silhouette),
                  ch = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla$ch),
                  db = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla$db),
                  average = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla$average)
                )
              }
            }
            
            # ============================================================
            # MCLA with Louvain Community Detection
            # ============================================================
            if ("MCLA_Louvain" %in% ensemble_methods) {
              message("Running MCLA_Louvain algorithm...")
              
              mcla_louvain_ensemble <- function(H_weighted, k = NULL, resolution = 1.0) {
                set.seed(42)
                n_hyperedges <- ncol(H_weighted)
                
                J <- matrix(0, n_hyperedges, n_hyperedges)
                
                for (i in 1:(n_hyperedges-1)) {
                  for (j in (i+1):n_hyperedges) {
                    intersection <- sum(pmin(H_weighted[, i], H_weighted[, j]))
                    union <- sum(pmax(H_weighted[, i], H_weighted[, j]))
                    
                    if (union > 0) {
                      J[i, j] <- intersection / union
                      J[j, i] <- J[i, j]  
                    }
                  }
                }
                
                g <- igraph::graph_from_adjacency_matrix(J, mode = "undirected", weighted = TRUE)
                
                louvain_result <- igraph::cluster_louvain(g)
                meta_clusters <- igraph::membership(louvain_result)
                
                k_actual <- length(unique(meta_clusters))
                
                if (!is.null(k) && k != k_actual) {
                  warning(paste("Louvain algoritmas??", k_actual, "k??me buldu, belirtilen k =", k, "de??erinden farkl??."))
                }
                
                n_samples <- nrow(H_weighted)
                cluster_association <- matrix(0, n_samples, k_actual)
                
                for (i in 1:k_actual) {
                  meta_cluster_i <- which(meta_clusters == i)
                  if (length(meta_cluster_i) > 0) {
                    cluster_association[, i] <- rowSums(H_weighted[, meta_cluster_i, drop = FALSE])
                  }
                }
                
                final_clusters <- apply(cluster_association, 1, which.max)
                
                return(as.integer(final_clusters))
              }
              
              results$ensemble_clusters$mcla_louvain <- list(
                standard = mcla_louvain_ensemble(H),
                silhouette = mcla_louvain_ensemble(H_sil),
                ch = mcla_louvain_ensemble(H_ch),
                db = mcla_louvain_ensemble(H_db),
                average = mcla_louvain_ensemble(H_ave)
              )

              message("Computing MCLA_Louvain quality indices...")
              .qi_mcla_lou <- list(
                standard   = list(data=HH,      cl=results$ensemble_clusters$mcla_louvain$standard,   nm="MCLA_Louvain_standard"),
                silhouette = list(data=HH_sil,  cl=results$ensemble_clusters$mcla_louvain$silhouette, nm="MCLA_Louvain_silhouette"),
                ch         = list(data=HH_ch,   cl=results$ensemble_clusters$mcla_louvain$ch,         nm="MCLA_Louvain_ch"),
                db         = list(data=HH_db,   cl=results$ensemble_clusters$mcla_louvain$db,         nm="MCLA_Louvain_db"),
                average    = list(data=HH_ave,  cl=results$ensemble_clusters$mcla_louvain$average,    nm="MCLA_Louvain_average")
              )
              results$quality_indices$mcla_louvain <- .par_lapply(.qi_mcla_lou, function(t)
                calculate_quality_indices(t$data, t$cl, t$nm))

              if (!is.null(true_labels)) {
                results$ensemble_ari$mcla_louvain <- list(
                  standard = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_louvain$standard),
                  silhouette = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_louvain$silhouette),
                  ch = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_louvain$ch),
                  db = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_louvain$db),
                  average = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_louvain$average)
                )
              }
            }
            
            # ============================================================
            # MCLA with Leiden Community Detection
            # ============================================================
            if ("MCLA_Leiden" %in% ensemble_methods) {
              message("Running MCLA_Leiden algorithm...")
              
              mcla_leiden_ensemble <- function(H_weighted, k = NULL, resolution = 1.0) {
                set.seed(42)
                n_hyperedges <- ncol(H_weighted)
                
                J <- matrix(0, n_hyperedges, n_hyperedges)
                
                for (i in 1:(n_hyperedges-1)) {
                  for (j in (i+1):n_hyperedges) {
                    intersection <- sum(pmin(H_weighted[, i], H_weighted[, j]))
                    union <- sum(pmax(H_weighted[, i], H_weighted[, j]))
                    
                    if (union > 0) {
                      J[i, j] <- intersection / union
                      J[j, i] <- J[i, j] 
                    }
                  }
                }
                
                g <- igraph::graph_from_adjacency_matrix(J, mode = "undirected", weighted = TRUE)
                
                leiden_result <- igraph::cluster_leiden(g, resolution = resolution, objective_function = "CPM")
                meta_clusters <- igraph::membership(leiden_result)
                
                k_actual <- length(unique(meta_clusters))
                
                if (!is.null(k) && k != k_actual) {
                  warning(paste("Leiden algoritmas??", k_actual, "k??me buldu, belirtilen k =", k, "de??erinden farkl??."))
                }
                n_samples <- nrow(H_weighted)
                cluster_association <- matrix(0, n_samples, k_actual)
                
                for (i in 1:k_actual) {
                  meta_cluster_i <- which(meta_clusters == i)
                  if (length(meta_cluster_i) > 0) {
                    cluster_association[, i] <- rowSums(H_weighted[, meta_cluster_i, drop = FALSE])
                  }
                }
                
                final_clusters <- apply(cluster_association, 1, which.max)
                
                return(as.integer(final_clusters))
              }
            
            # Bootstrap-based stability optimisation for MCLA Leiden.
            # Ground-truth labels are NOT used at any stage.
            # Workflow (Monti et al. 2003 framework, adapted for hyperedge space):
            #   1. Precompute full Jaccard matrix J once (resolution-independent)
            #   2. Run MCLA+Leiden on full H → reference partition C_ref
            #   2. Repeat n_bootstrap times:
            #        a. Draw 80 % of hyperedges (columns) without replacement
            #        b. J_sub = J[sample_cols, sample_cols]  — O(1), no recomputation
            #        c. Run Leiden on J_sub → meta-clusters → project to cells → C_sub
            #        d. ARI(C_ref, C_sub)  — both purely algorithmic
            #   3. Stability score = mean ARI; select resolution with highest score
            optimize_resolution_mcla <- function(H_weighted, label = "MCLA",
                                                 n_bootstrap = 10,
                                                 subsample_fraction = 0.8) {
              res_range <- seq(0.2, 2.0, by = 0.2)
              M <- ncol(H_weighted)   # hyperedge count
              N <- nrow(H_weighted)   # cell count

              # Precompute full Jaccard matrix once — subsamples reuse J[cols, cols]
              J_full <- matrix(0, M, M)
              for (i in seq_len(M - 1)) {
                for (j in (i + 1):M) {
                  inter <- sum(pmin(H_weighted[, i], H_weighted[, j]))
                  uni   <- sum(pmax(H_weighted[, i], H_weighted[, j]))
                  if (uni > 0) { J_full[i, j] <- inter / uni; J_full[j, i] <- J_full[i, j] }
                }
              }

              # Helper: run Leiden on a Jaccard (sub)matrix, project to cell labels
              run_leiden_mcla <- function(J_mat, H_mat, r) {
                if (ncol(J_mat) < 2) return(NULL)
                g <- igraph::graph_from_adjacency_matrix(
                  J_mat, mode = "undirected", weighted = TRUE)
                lr <- tryCatch(
                  igraph::cluster_leiden(g, resolution = r,
                                         objective_function = "modularity"),
                  error = function(e) NULL)
                if (is.null(lr)) return(NULL)
                meta <- igraph::membership(lr)
                k    <- length(unique(meta))
                if (k < 2) return(NULL)
                assoc <- matrix(0, nrow(H_mat), k)
                for (i in seq_len(k)) {
                  idx <- which(meta == i)
                  if (length(idx) > 0)
                    assoc[, i] <- rowSums(H_mat[, idx, drop = FALSE])
                }
                as.integer(apply(assoc, 1, which.max))
              }

              # Export current-scope state to workers
              if (!is.null(.cl)) {
                parallel::clusterExport(.cl,
                  c("J_full", "H_weighted", "M", "n_bootstrap", "subsample_fraction"),
                  envir = environment())
                parallel::clusterEvalQ(.cl, { library(igraph); library(mclust) })
              }

              stab_results <- .par_lapply(as.list(res_range), function(r) {
                # run_leiden_mcla inlined for worker self-containedness
                .run_leiden_mcla <- function(J_mat, H_mat, res) {
                  if (ncol(J_mat) < 2) return(NULL)
                  g <- igraph::graph_from_adjacency_matrix(J_mat, mode = "undirected", weighted = TRUE)
                  lr <- tryCatch(
                    igraph::cluster_leiden(g, resolution = res, objective_function = "modularity",
                                          n_iterations = 2L),
                    error = function(e) NULL)
                  if (is.null(lr)) return(NULL)
                  meta <- igraph::membership(lr)
                  k    <- length(unique(meta))
                  if (k < 2) return(NULL)
                  assoc <- matrix(0, nrow(H_mat), k)
                  for (i in seq_len(k)) {
                    idx <- which(meta == i)
                    if (length(idx) > 0) assoc[, i] <- rowSums(H_mat[, idx, drop = FALSE])
                  }
                  as.integer(apply(assoc, 1, which.max))
                }

                set.seed(42)
                ref_clusters <- .run_leiden_mcla(J_full, H_weighted, r)
                if (is.null(ref_clusters) || length(unique(ref_clusters)) < 2)
                  return(list(r = r, stab = -Inf))

                ari_scores <- numeric(n_bootstrap)
                for (b in seq_len(n_bootstrap)) {
                  set.seed(42 + b)
                  cols   <- sample(M, round(subsample_fraction * M), replace = FALSE)
                  J_sub  <- J_full[cols, cols]
                  H_sub  <- H_weighted[, cols, drop = FALSE]
                  sub_cl <- .run_leiden_mcla(J_sub, H_sub, r)
                  if (is.null(sub_cl) || length(unique(sub_cl)) < 2) {
                    ari_scores[b] <- 0; next
                  }
                  ari_val <- tryCatch(
                    mclust::adjustedRandIndex(ref_clusters, sub_cl),
                    error = function(e) NA_real_)
                  ari_scores[b] <- if (!is.finite(ari_val)) 0 else ari_val
                }
                stab <- mean(ari_scores, na.rm = TRUE)
                list(r = r, stab = if (!is.finite(stab) || stab <= 0) -Inf else stab)
              })

              best_stabs <- vapply(stab_results, `[[`, numeric(1), "stab")
              best_idx   <- which.max(best_stabs)
              if (length(best_idx) == 0 || !is.finite(best_stabs[best_idx]) || best_stabs[best_idx] <= 0) {
                best_res <- 1.0; best_stability <- 0
              } else {
                best_res       <- stab_results[[best_idx]]$r
                best_stability <- best_stabs[best_idx]
              }
              message(sprintf("    %s Leiden optimum resolution: %.2f (bootstrap stability: %.4f)",
                              label, best_res, best_stability))
              return(best_res)
            }

            # Silhouette-based resolution selection for MCLA Leiden.
            optimize_resolution_mcla_sil <- function(H_weighted, label = "MCLA") {
              res_range <- seq(0.2, 2.0, by = 0.2)
              n_he <- ncol(H_weighted)
              J <- matrix(0, n_he, n_he)
              for (i in seq_len(n_he - 1)) {
                for (j in (i + 1):n_he) {
                  inter <- sum(pmin(H_weighted[, i], H_weighted[, j]))
                  uni   <- sum(pmax(H_weighted[, i], H_weighted[, j]))
                  if (uni > 0) { J[i, j] <- inter / uni; J[j, i] <- J[i, j] }
                }
              }
              g_J <- igraph::graph_from_adjacency_matrix(J, mode = "undirected", weighted = TRUE)
              HH_local <- H_weighted %*% t(H_weighted)
              HH_local <- HH_local / max(HH_local)
              dist_mat  <- as.dist(1 - HH_local)
              assign_cells <- function(meta, H_mat) {
                k <- length(unique(meta))
                assoc <- matrix(0, nrow(H_mat), k)
                for (i in seq_len(k)) {
                  idx <- which(meta == i)
                  if (length(idx) > 0) assoc[, i] <- rowSums(H_mat[, idx, drop = FALSE])
                }
                as.integer(apply(assoc, 1, which.max))
              }
              best_res <- NA; best_score <- -Inf
              for (r in res_range) {
                set.seed(42)
                lr <- tryCatch(
                  igraph::cluster_leiden(g_J, resolution = r, objective_function = "modularity"),
                  error = function(e) NULL)
                if (is.null(lr)) next
                meta <- igraph::membership(lr)
                if (length(unique(meta)) < 2) next
                cl <- assign_cells(meta, H_weighted)
                sc <- tryCatch(
                  mean(cluster::silhouette(cl, dist_mat)[, 3], na.rm = TRUE),
                  error = function(e) NA_real_)
                if (!is.finite(sc)) next
                if (sc > best_score) { best_score <- sc; best_res <- r }
              }
              if (is.na(best_res)) best_res <- 1.0
              message(sprintf("    %s Leiden optimum resolution: %.2f (silhouette: %.4f)",
                              label, best_res, ifelse(is.finite(best_score), best_score, 0)))
              return(best_res)
            }

            # Dispatch: choose optimiser based on leiden_method
            run_opt_mcla <- function(H_mat, label) {
              if (leiden_method == "silhouette")
                optimize_resolution_mcla_sil(H_mat, label)
              else
                optimize_resolution_mcla(H_mat, label, n_bootstrap = leiden_n_bootstrap)
            }

            resolution_params <- list()
            resolution_params$standard   <- run_opt_mcla(H,      "MCLA standard")
            resolution_params$silhouette <- run_opt_mcla(H_sil,  "MCLA silhouette")
            resolution_params$ch         <- run_opt_mcla(H_ch,   "MCLA ch")
            resolution_params$db         <- run_opt_mcla(H_db,   "MCLA db")
            resolution_params$average    <- run_opt_mcla(H_ave,  "MCLA average")


            results$ensemble_clusters$mcla_leiden <- list(
              standard = mcla_leiden_ensemble(H, resolution = resolution_params$standard),
              silhouette = mcla_leiden_ensemble(H_sil, resolution = resolution_params$silhouette),
              ch = mcla_leiden_ensemble(H_ch, resolution = resolution_params$ch),
              db = mcla_leiden_ensemble(H_db, resolution = resolution_params$db),
              average = mcla_leiden_ensemble(H_ave, resolution = resolution_params$average)
            )

            message("Computing MCLA_Leiden quality indices...")
            .qi_mcla_lei <- list(
              standard   = list(data=HH,      cl=results$ensemble_clusters$mcla_leiden$standard,   nm="MCLA_Leiden_standard"),
              silhouette = list(data=HH_sil,  cl=results$ensemble_clusters$mcla_leiden$silhouette, nm="MCLA_Leiden_silhouette"),
              ch         = list(data=HH_ch,   cl=results$ensemble_clusters$mcla_leiden$ch,         nm="MCLA_Leiden_ch"),
              db         = list(data=HH_db,   cl=results$ensemble_clusters$mcla_leiden$db,         nm="MCLA_Leiden_db"),
              average    = list(data=HH_ave,  cl=results$ensemble_clusters$mcla_leiden$average,    nm="MCLA_Leiden_average")
            )
            results$quality_indices$mcla_leiden <- .par_lapply(.qi_mcla_lei, function(t)
              calculate_quality_indices(t$data, t$cl, t$nm))

            if (!is.null(true_labels)) {
              results$ensemble_ari$mcla_leiden <- list(
                standard = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_leiden$standard),
                silhouette = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_leiden$silhouette),
                ch = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_leiden$ch),
                db = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_leiden$db),
                average = adjustedRandIndex(true_labels, results$ensemble_clusters$mcla_leiden$average)
              )
            }
          }
            # ============================================================
            # Hypergraph Spectral Clustering (HGSC)
            # ============================================================
            if ("HGSC" %in% ensemble_methods) {
              message("Running Hypergraph Spectral Clustering(HGSC) algorithm...")
              
              hgsc_ensemble <- function(H_weighted, k=NULL) {
                # Calculate the Hypergraph Laplacian matrix
                D_v <- diag(rowSums(H_weighted))  # Vertex degree matrix
                D_e <- diag(colSums(H_weighted))  # Edge degree matrix
                
                D_v_inv_sqrt <- diag(1 / sqrt(diag(D_v)))
                D_e_inv <- diag(1 / diag(D_e))
                
                # Normalized Laplacian matrix
                L <- diag(nrow(H_weighted)) - D_v_inv_sqrt %*% H_weighted %*% D_e_inv %*% t(H_weighted) %*% D_v_inv_sqrt
                
                estimate_optimal_k <- function(L) {
                  # Calculate the eigenvalues of the Laplacian matrix
                  eigen_values <- eigen(L, only.values = TRUE)$values
                  
                  # Sort Eigenvalues from smallest to largest
                  eigen_values <- sort(eigen_values)
                  
                  # Calculate the differences between consecutive eigenvalues
                  eigen_gaps <- diff(eigen_values)
                  
                  # Find the index of the largest gap 
                  # This refers to the optimal number of clusters
                  k_est <- which.max(eigen_gaps) + 1
                  
                  return(k_est)
                }
                
                if(is.null(k)) {
                  k <- estimate_optimal_k(L)
                }
                # Eigenvalues and vectors
                eigen_result <- eigen(L)
                
                eigenvalues_sorted <- sort(eigen_result$values, index.return = TRUE)
                U <- eigen_result$vectors[, eigenvalues_sorted$ix[1:k]]
                
                kmeans_result <- kmeans(U, centers = k, nstart = 20)
                
                return(kmeans_result$cluster)
              }
              
              results$ensemble_clusters$hgsc <- list(
                standard = hgsc_ensemble(HH),
                silhouette = hgsc_ensemble(HH_sil),
                ch = hgsc_ensemble(HH_ch),
                db = hgsc_ensemble(HH_db),
                average = hgsc_ensemble(HH_ave)
              )

              message("Computing HGSC quality indices...")
              .qi_hgsc <- list(
                standard   = list(data=HH,      cl=results$ensemble_clusters$hgsc$standard,   nm="HGSC_standard"),
                silhouette = list(data=HH_sil,  cl=results$ensemble_clusters$hgsc$silhouette, nm="HGSC_silhouette"),
                ch         = list(data=HH_ch,   cl=results$ensemble_clusters$hgsc$ch,         nm="HGSC_ch"),
                db         = list(data=HH_db,   cl=results$ensemble_clusters$hgsc$db,         nm="HGSC_db"),
                average    = list(data=HH_ave,  cl=results$ensemble_clusters$hgsc$average,    nm="HGSC_average")
              )
              results$quality_indices$hgsc <- .par_lapply(.qi_hgsc, function(t)
                calculate_quality_indices(t$data, t$cl, t$nm))

              if (!is.null(true_labels)) {
                results$ensemble_ari$hgsc <- list(
                  standard = adjustedRandIndex(true_labels, results$ensemble_clusters$hgsc$standard),
                  silhouette = adjustedRandIndex(true_labels, results$ensemble_clusters$hgsc$silhouette),
                  ch = adjustedRandIndex(true_labels, results$ensemble_clusters$hgsc$ch),
                  db = adjustedRandIndex(true_labels, results$ensemble_clusters$hgsc$db),
                  average = adjustedRandIndex(true_labels, results$ensemble_clusters$hgsc$average)
                )
              }
            }
            
            ensemble_results <- new("EnsembleResults",
                                    ensemble_clusters = results$ensemble_clusters,
                                    ensemble_ari = results$ensemble_ari,
                                    ensemble_quality = results$quality_indices)
            
            
            object@ensemble_results <- ensemble_results
            
            
            return(object)
          }
)
